trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo K8S Terraform Azure!
  displayName: 'Run a one-line script'
- task: DownloadSecureFile@1
  name: publickey
  inputs:
    secureFile: 'azure_rsa.pub'

- task: TerraformCLI@0
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure'
    backendType: 'azurerm'
    backendServiceArm: 'Microsoft Azure Sponsorship - MVP(1199b626-a317-4559-9289-caba7859ee88)'
    ensureBackend: true
    backendAzureRmResourceGroupName: 'backend-rg'
    backendAzureRmResourceGroupLocation: 'koreacentral'
    backendAzureRmStorageAccountName: 'storageacctnamexm1'
    backendAzureRmContainerName: 'storageaccntcontainer'
    backendAzureRmKey: 'k8.tfstate'
    allowTelemetryCollection: true
- task: TerraformCLI@0
  inputs:
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure'
    environmentServiceName: 'Microsoft Azure Sponsorship - MVP(1199b626-a317-4559-9289-caba7859ee88)'
    commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_public_key=$(publickey.secureFilePath)'
    allowTelemetryCollection: true